### PR TITLE
Validate trust on Wallet Provider

### LINKED ISSUE #454: Validate trust on Wallet Providers
Currenntly PID Issuer supports key attestations (WUAs) sent as part of credential issuance requests. Validation rules of key attestations are implemented with one exception, validating that the WUA is comming from a trusted `Wallet Provider`. 

~~Issuer needs to be extended to support trust on Wallet Providers based on:~~ 
~~- [ ] Trusted Lists as specified by ETSI 119 612 or~~
~~- [ ] A configured keystore containing the public keys of trusted wallet providers~~

~~A similar mechanism has been already implemented in verifier backend service as part of issue [Use LOTL to obtain issuer trust anchors #277](https://github.com/eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt/issues/277) with [this PR](https://github.com/eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt/pull/316).~~  

~~In the context of this issue only one keystore needs to be loaded containing certificates of trusted wallet providers.~~
~~- [ ] The trusted certificates must be passed to the configured `VerifyKeyAttestation` component when configured in [issuer's spring context](https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer/blob/main/src/main/kotlin/eu/europa/ec/eudi/pidissuer/PidIssuerApplication.kt#L458)~~

ETSI TS 119 602 introduces the concept of "Lists of Trusted Entities" and its data model aims to be an abstract generalization of the existing specifications of trusted lists provided in ETSI TS 119 612. In the context of this standard wallet providers are identified as an entity that will be notified by Member States in accordance with the applicable European legislation.

Annex E of ETSI TS 119 602 specifies the structure and serialization of the wallet providers list. Wallet providers is defined as an entity with LoTE type 

> http://uri.etsi.org/19602/LoTEType/EUWalletProvidersList

A new service ([eudi-srv-trust-validator](https://github.com/eu-digital-identity-wallet/eudi-srv-trust-validator)) has been implemented to validate participation of an entity's X5C certificate (or certificate chain) in lists  of trust. Currently the service is sourcing and periodically refreshing ETSI 119 612 lists and consulting them to identify the existence of specific service type in lists. In the future this service will be extended to also source ETSI 119 602 Lists of Trusted Entities. Service also provides loading trusted certificates or certificate chains from configured keystores as an alternative trust source.

- [ ] Kotlin issuer should be updated to integrate with trust validator service to validate that a WUA is coming from a trusted wallet provider.
- [ ] Until LoTEs can be sourced, trust validator service should use a dedicated keystore as the wallet providers trust source.

### PR DESCRIPTION
**Pull request by atsant**
Closes #454

### CODE REVIEW

File: src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/trust/IsTrustedKeyAttestationIssuerExtensions.kt [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+import java.io.ByteArrayInputStream
+import java.net.URI
+import java.security.cert.CertificateFactory
+import java.security.cert.X509Certificate
+
+fun IsTrustedKeyAttestationIssuer.Companion.usingTrustValidatorService(
+    webClient: WebClient,
+    service: URI,
+): IsTrustedKeyAttestationIssuer = IsTrustedKeyAttestationIssuer { x5c ->
+    val body = TrustQueryRequest(x5c, "PID")
```
Comment (atsant) [inline src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/trust/IsTrustedKeyAttestationIssuerExtensions.kt]: This should be change to `WUA`

File: src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/VerifyKeyAttestation.kt [hunk 2]
```diff
@@ -59,31 +70,44 @@ internal class VerifyKeyAttestation(
...
+                walletProviderSigningKey.ensureTrustWalletProvider()
+            }
 
             keyAttestation.attestedKeys to nonce
         }
     }
 
-    private fun KeyAttestationJWT.extractSigningKey(): JWK {
+    private suspend fun WalletProviderSigningKey.X5C.ensureTrustWalletProvider() {
+        when (val result = isTrustedKeyAttestationIssuer(x5c)) {
```
Comment (dzarras) [inline src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/VerifyKeyAttestation.kt]:
```kotlin
require(result is TrustResult.IsTrusted) {
   "Key attestation is not issued by a trusted wallet provider"
}
```

File: src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/VerifyKeyAttestation.kt [hunk 3]
```diff
@@ -37,18 +39,27 @@ import eu.europa.ec.eudi.pidissuer.domain.KeyAttestationJWT
...
 import kotlin.time.Instant
 
-internal val SkipRevocation: PKIXParameters.() -> Unit = { isRevocationEnabled = false }
+sealed interface TrustResult {
+    object IsTrusted : TrustResult
+    object IsUntrusted : TrustResult
+    class ServiceFailure(val reason: String, val throwable: Throwable) : TrustResult
+}
+
+fun interface IsTrustedKeyAttestationIssuer {
```
Comment (vafeini) [inline src/main/kotlin/eu/europa/ec/eudi/pidissuer/adapter/out/jose/VerifyKeyAttestation.kt]: @atsant @dzarras  I believe interface `IsTrustedKeyAttestationIssuer`  along with `TrustResult` should be moved under a 'trust' out port.
